apiVersion: apps/v1
kind: Deployment
metadata:
     annotations:
          kompose.cmd: kompose --file deploy.yaml convert
          kompose.version: 1.21.0 ()
     creationTimestamp: null
     labels:
          io.kompose.service: server
     name: server
     namespace: ingress-nginx
spec:
     replicas: 1
     selector:
          matchLabels:
               io.kompose.service: server
     strategy: {}
     template:
          metadata:
               annotations:
                    kompose.cmd: kompose --file deploy.yaml convert
                    kompose.version: 1.21.0 ()
               creationTimestamp: null
               labels:
                    io.kompose.service: server
          spec:
               containers:
                    - args:
                           - npm
                           - start
                           - server.js
                      env:
                           - name: AWS_ACCESS_KEY_ID
                             valueFrom:
                                  secretKeyRef:
                                       name: awsaccessket
                                       key: AWS_ACCESS_KEY_ID
                           - name: AWS_BUCKET_NAME
                             valueFrom:
                                  secretKeyRef:
                                       name: bucketname
                                       key: AWS_BUCKET_NAME
                           - name: AWS_REGION
                             valueFrom:
                                  secretKeyRef:
                                       name: region
                                       key: AWS_REGION
                           - name: AWS_SECRET_ACCESS_KEY
                             valueFrom:
                                  secretKeyRef:
                                       name: awssecretkey
                                       key: AWS_SECRET_ACCESS_KEY
                           - name: AWS_Uploaded_File_URL_LINK
                             valueFrom:
                                  secretKeyRef:
                                       name: bucketlink
                                       key: AWS_Uploaded_File_URL_LINK
                           - name: MONGO_URI
                             valueFrom:
                                  secretKeyRef:
                                       name: mongo-prod
                                       key: MONGO_URI
                           - name: STRIPE_SECRET_KEY
                             valueFrom:
                                  secretKeyRef:
                                       name: stripekey
                                       key: STRIPE_SECRET_KEY
                           - name: secretOrKey
                             valueFrom:
                                  secretKeyRef:
                                       name: secret-or-key
                                       key: secretOrKey
                           - name: NODE_ENV
                             valueFrom:
                                  secretKeyRef:
                                       name: node
                                       key: NODE_ENV
                           - name: ALGOLIA_ID
                             valueFrom:
                                  secretKeyRef:
                                       name: algolia-id
                                       key: ALGOLIA_ID
                           - name: ALGOLIA_KEY
                             valueFrom:
                                  secretKeyRef:
                                       name: algoliakey
                                       key: ALGOLIA_KEY
                           - name: jack
                             valueFrom:
                                  secretKeyRef:
                                       name: jack
                                       key: jack
                           - name: chris
                             valueFrom:
                                  secretKeyRef:
                                       name: chris
                                       key: chris
                           - name: blaze
                             valueFrom:
                                  secretKeyRef:
                                       name: blaze
                                       key: blaze
                           - name: SENDGRID_API_KEY
                             valueFrom:
                                  secretKeyRef:
                                       name: sendgrid
                                       key: SENDGRID_API_KEY
                      image: gcr.io/quirkshop-1585189206879/server:v0.33
                      imagePullPolicy: Always
                      name: server
                      ports:
                           - containerPort: 5000
                      resources: {}
               restartPolicy: Always
               serviceAccountName: ""
               volumes: null
status: {}
