version: "3"

services:
     server:
          build: ./server
          container_name: sarah
          ports:
               - "5000:5000"
          env_file: .env
          # command: "npm start"
     client:
          build: ./client
          container_name: mimi
          ports:
               - "3000:3000"

          depends_on:
               - server
          # command: "yarn start"

     janus:
          build: ./janus
          container_name: janus_gateway
          ports:
               - 8088:8088
               - 8188:8188
               - 7188:7188
          volumes:
               - ./janus/etc:/opt/janus/etc/janus
          command: "/opt/janus/bin/janus -S stun.l.google.com:19302"
     heidi:
          build: ./heidi
          container_name: heidi
          ports:
               - 4000:4000
          depends_on:
               - client
               - server
               - janus
          # command: "bin/heidi start"
