use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
secret_key_base =
  System.get_env("SECRET_KEY_BASE") || "nNt7cf4H60llt92WlTc+QkW19LKZ5CY+GZtSRvH2bbqvRnAucje8jlaDN+fMRQWT"


# config :heidi_web, 

config :heidi_web, BroadcastWeb.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"}|| 4000],
  url: [scheme: "https", host: "quirkshop.org", port: 4000],
  force_ssl: [hsts: true],
  server: true,
  root: ".",
  version: Application.spec(:heidi_web, :vsn)

  # load_from_system_env: true,
  # url: [host: System.get_env("IP_ADDRESS"), port: 4000],
  # server: true,
  # http: [port:  System.get_env("PORT")],
  # url: [scheme: "https", host: System.get_env("IP_ADDRESS"), port: 443],
  # secret_key_base: secret_key_base
  # force_ssl: [rewrite_on: [:x_forwarded_proto], exclude: ["localhost", System.get_env("IP_ADDRESS")]],  
  # http: [:inet6, port: System.get_env("PORT") || 4000],
  
  # load_from_system_env: true,
  # http: [port: {:system, "PORT"}|| 4000],
  # force_ssl: [rewrite_on: [:x_forwarded_proto]],
  # check_origin: false,
  # # url: [scheme: "https", host: System.get_env("IP_ADDRESS"), port: 4000],
  # server: true,
  # root: ".",
  # version: Application.spec(:heidi_web, :vsn)
  # # https: [
  #   port: 4000,
  #   otp_app: :heidi_web


  # ]

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :heidi_web, BroadcastWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :heidi_web, BroadcastWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Do not print debug messages in production
config :logger, level: :info

# Set up prod environment flag
config :heidi, environment: System.get_env("ENVIRONMENT") || :prod

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
