apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-production
  namespace: ingress-nginx
spec:
  secretName: staging-ssl
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.quirkshop.org"
  dnsNames:
    - "quirkshop.org"
    - "*.quirkshop.org"
  acme:
    config:
      - dns01:
          provider: clouddns
          hostedZoneName: zone-1
        domains:
          - "quirkshop.org"
          - "*.quirkshop.org"
